logging:
  level:
    root: INFO
    com.hgh.springbootdemo: DEBUG


spring:
  datasource:
    name: seimi
    type: com.alibaba.druid.pool.DruidDataSource
    url : jdbc:mysql://192.168.0.241:3306/Bss-max?characterEncoding=utf8&useUnicode=true
    username: bss_max
    password: bss_max~123
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  http:
    multipart:
      max-file-size: 10Mb
      maxRequestSize: 10Mb
#  freemarker:
#    allow-request-override: false
#    cache: true
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: false
#    expose-session-attributes: false
#    expose-spring-macro-helpers: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

server:
  port: 8081


